In [1]:
import cv2
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from keras.utils import to_categorical
from keras.datasets import mnist, cifar10
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
import matplotlib.pyplot as plt

In [2]:
image = cv2.imread('picture2.jpg')
cv2.imwrite('compressed_jpeg.jpg', image, [cv2.IMWRITE_JPEG_QUALITY, 50])  # JPEG Compression
cv2.imwrite('compressed_png.png', image, [cv2.IMWRITE_PNG_COMPRESSION, 9])

True

In [3]:
def build_mnist_model():
    model = Sequential([
        Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
        MaxPooling2D((2,2)),
        Conv2D(64, (3,3), activation='relu'),
        MaxPooling2D((2,2)),
        Flatten(),
        Dense(128, activation='relu'),
        Dropout(0.5),
        Dense(10, activation='softmax')
    ])
    return model

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
y_train, y_test = to_categorical(y_train, 10), to_categorical(y_test, 10)

x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

model = build_mnist_model()
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=50, validation_split=0.2)


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - accuracy: 0.8471 - loss: 0.4788 - val_accuracy: 0.9822 - val_loss: 0.0587
Epoch 2/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9741 - loss: 0.0872 - val_accuracy: 0.9880 - val_loss: 0.0439
Epoch 3/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9807 - loss: 0.0638 - val_accuracy: 0.9892 - val_loss: 0.0367
Epoch 4/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9843 - loss: 0.0516 - val_accuracy: 0.9898 - val_loss: 0.0379
Epoch 5/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9874 - loss: 0.0403 - val_accuracy: 0.9902 - val_loss: 0.0377
Epoch 6/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9892 - loss: 0.0350 - val_accuracy: 0.9906 - val_loss: 0.0359
Epoch 7/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9914 - loss: 0.0287 - val_accuracy: 0.9914 - val_loss: 0.0317
Epoch 8/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9913 - loss: 0.0261

In [4]:
def build_cifar10_model():
    model = Sequential([
        Conv2D(32, (3,3), activation='relu', input_shape=(32,32,3)),
        MaxPooling2D((2,2)),
        Conv2D(64, (3,3), activation='relu'),
        MaxPooling2D((2,2)),
        Flatten(),
        Dense(128, activation='relu'),
        Dropout(0.5),
        Dense(10, activation='softmax')
    ])
    return model

(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
y_train, y_test = to_categorical(y_train, 10), to_categorical(y_test, 10)

model = build_cifar10_model()
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=50, validation_split=0.2)

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 3s 0us/step
Epoch 1/50
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.3229 - loss: 1.8156 - val_accuracy: 0.5230 - val_loss: 1.3606
Epoch 2/50
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.5134 - loss: 1.3611 - val_accuracy: 0.5922 - val_loss: 1.1603
Epoch 3/50
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.5754 - loss: 1.2027 - val_accuracy: 0.6356 - val_loss: 1.0486
Epoch 4/50
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.6115 - loss: 1.1050 - val_accuracy: 0.6369 - val_loss: 1.0230
Epoch 5/50
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.6320 - loss: 1.0375 - val_accuracy: 0.6578 - val_loss: 0.9666
Epoch 6/50
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.6533 - loss: 0.9763 - val_accuracy: 0.6685 - val_loss: 0.9355
Epoch 7/50
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.6719 - loss: 0.9281 - val_accuracy: 0.6840 - val_loss: 0.9000
Epoch 8/50
1250/1250 ━━━━━━━━━━━━━━━

In [5]:
y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)
print(classification_report(y_true, y_pred_classes))
print(confusion_matrix(y_true, y_pred_classes))

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
              precision    recall  f1-score   support

           0       0.73      0.74      0.74      1000
           1       0.85      0.79      0.82      1000
           2       0.60      0.58      0.59      1000
           3       0.51      0.50      0.50      1000
           4       0.67      0.65      0.66      1000
           5       0.60      0.58      0.59      1000
           6       0.77      0.78      0.77      1000
           7       0.74      0.73      0.74      1000
           8       0.79      0.82      0.80      1000
           9       0.75      0.83      0.79      1000

    accuracy                           0.70     10000
   macro avg       0.70      0.70      0.70     10000
weighted avg       0.70      0.70      0.70     10000

[[744  17  57  19  21   3   5   9  84  41]
 [ 24 791   6   9   2   1  11   4  30 122]
 [ 68   8 580  55  86  64  70  37  19  13]
 [ 25   8  65 496  70 187  61  53  11  24]
 [ 25   6  68  62 653  31  5