In [ ]:
import cv2
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from keras.utils import to_categorical
from keras.datasets import mnist, cifar10
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
import matplotlib.pyplot as plt

In [ ]:
image = cv2.imread('Picture.jpg')
cv2.imwrite('compressed_i.jpg', image, [cv2.IMWRITE_JPEG_QUALITY, 50])
cv2.imwrite('compressed_p.png', image, [cv2.IMWRITE_PNG_COMPRESSION, 9])

True

In [ ]:
def build_mnist_model():
    model = Sequential([
        Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
        MaxPooling2D((2,2)),
        Conv2D(64, (3,3), activation='relu'),
        MaxPooling2D((2,2)),
        Flatten(),
        Dense(128, activation='relu'),
        Dropout(0.5),
        Dense(10, activation='softmax')
    ])
    return model

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
y_train, y_test = to_categorical(y_train, 10), to_categorical(y_test, 10)

x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

model = build_mnist_model()
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=10, validation_split=0.2)


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8495 - loss: 0.4746 - val_accuracy: 0.9809 - val_loss: 0.0608
Epoch 2/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9720 - loss: 0.0934 - val_accuracy: 0.9887 - val_loss: 0.0396
Epoch 3/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9809 - loss: 0.0641 - val_accuracy: 0.9881 - val_loss: 0.0458
Epoch 4/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9856 - loss: 0.0466 - val_accuracy: 0.9901 - val_loss: 0.0349
Epoch 5/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9881 - loss: 0.0380 - val_accuracy: 0.9905 - val_loss: 0.0359
Epoch 6/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9908 - loss: 0.0296 - val_accuracy: 0.9909 - val_loss: 0.0367
Epoch 7/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9897 - loss: 0.0320 - val_accuracy: 0.9908 - val_loss: 0.0336
Epoch 8/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9920 - loss: 0.02

In [ ]:
def build_cifar10_model():
    model = Sequential([
        Conv2D(32, (3,3), activation='relu', input_shape=(32,32,3)),
        MaxPooling2D((2,2)),
        Conv2D(64, (3,3), activation='relu'),
        MaxPooling2D((2,2)),
        Flatten(),
        Dense(128, activation='relu'),
        Dropout(0.5),
        Dense(10, activation='softmax')
    ])
    return model

(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
y_train, y_test = to_categorical(y_train, 10), to_categorical(y_test, 10)

model = build_cifar10_model()
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=50, validation_split=0.2)

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 19s 0us/step
Epoch 1/50
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.3073 - loss: 1.8684 - val_accuracy: 0.5138 - val_loss: 1.3965
Epoch 2/50
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.4903 - loss: 1.4189 - val_accuracy: 0.5921 - val_loss: 1.1732
Epoch 3/50
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.5569 - loss: 1.2475 - val_accuracy: 0.6130 - val_loss: 1.1158
Epoch 4/50
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.5970 - loss: 1.1478 - val_accuracy: 0.5978 - val_loss: 1.1226
Epoch 5/50
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.6179 - loss: 1.0833 - val_accuracy: 0.6587 - val_loss: 0.9936
Epoch 6/50
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.6401 - loss: 1.0253 - val_accuracy: 0.6610 - val_loss: 0.9829
Epoch 7/50
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.6566 - loss: 0.9817 - val_accuracy: 0.6538 - val_loss: 0.9850
Epoch 8/50
1250/1250 ━━━━━━━━━━━━━━

In [ ]:
y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)
print(classification_report(y_true, y_pred_classes))
print(confusion_matrix(y_true, y_pred_classes))

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
              precision    recall  f1-score   support

           0       0.74      0.72      0.73      1000
           1       0.84      0.80      0.82      1000
           2       0.62      0.57      0.59      1000
           3       0.48      0.52      0.50      1000
           4       0.66      0.62      0.64      1000
           5       0.59      0.60      0.60      1000
           6       0.75      0.78      0.76      1000
           7       0.72      0.76      0.74      1000
           8       0.81      0.79      0.80      1000
           9       0.77      0.82      0.79      1000

    accuracy                           0.70     10000
   macro avg       0.70      0.70      0.70     10000
weighted avg       0.70      0.70      0.70     10000

[[723  16  56  27  19  10   8  20  77  44]
 [ 24 795   9  18   1   7  11   5  29 101]
 [ 68   6 566  80  82  85  58  38   9   8]
 [ 16   9  80 522  58 165  61  57  15  17]
 [ 22   4  75  78 616  37  7