In [1]:
#task 1

In [2]:
import cv2
import numpy as np
from skimage import transform


In [3]:
img = cv2.imread(r"C:\Users\Pranshu Saini\Desktop\Picture1.jpg")
cv2.imshow('img', img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
# Linear Interpolation
img_linear = cv2.resize(img, (400, 400), interpolation=cv2.INTER_LINEAR)



cv2.imshow('Linear Interpolation', img_linear)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
img_nearest = cv2.resize(img, (400, 400), interpolation=cv2.INTER_NEAREST)
cv2.imshow('Nearest Neighbors', img_nearest)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
img_polynomial = transform.resize(img, (400, 400), mode='reflect')
cv2.imshow('img_polynomial', img_polynomial)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
 img_box_blur = cv2.blur(img, (6, 6))
cv2.imshow('Box Blurring', img_box_blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
img_gaussian_blur = cv2.GaussianBlur(img, (7,7), 0)
cv2.imshow('Gaussian Blurring', img_gaussian_blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_adaptive_blur = cv2.adaptiveThreshold(img_gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 2)
cv2.imshow('Adaptive Blurring', img_adaptive_blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
#task2

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_curve, auc
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neural_network import MLPClassifier
from tensorflow.keras.datasets import mnist


In [12]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(X_train.shape[0], -1).astype('float32') / 255.0
X_test = X_test.reshape(X_test.shape[0], -1).astype('float32') / 255.0


In [13]:
svm_model = SVC(kernel='linear', random_state=42)


In [14]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)


In [15]:
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

def evaluate_model(model, X, y):
    accuracies = cross_val_score(model, X, y, cv=kfold, scoring='accuracy')
    print(f'Accuracy: {accuracies.mean()}')

print("SVM Model Evaluation")
evaluate_model(svm_model, X_train, y_train)

print("Random Forest Model Evaluation")
evaluate_model(rf_model, X_train, y_train)


SVM Model Evaluation
Accuracy: 0.93315
Random Forest Model Evaluation
Accuracy: 0.9675


In [16]:
# Fit models on the training set
svm_model.fit(X_train, y_train)
rf_model.fit(X_train, y_train)

# Make predictions on test data
svm_pred = svm_model.predict(X_test)
rf_pred = rf_model.predict(X_test)


In [17]:
print("SVM Metrics:")
print(f'Accuracy: {accuracy_score(y_test, svm_pred)}')
print(f'Precision: {precision_score(y_test, svm_pred, average="macro")}')
print(f'Recall: {recall_score(y_test, svm_pred, average="macro")}')
print(f'F-Measure: {f1_score(y_test, svm_pred, average="macro")}')

print("Random Forest Metrics:")
print(f'Accuracy: {accuracy_score(y_test, rf_pred)}')
print(f'Precision: {precision_score(y_test, rf_pred, average="macro")}')
print(f'Recall: {recall_score(y_test, rf_pred, average="macro")}')
print(f'F-Measure: {f1_score(y_test, rf_pred, average="macro")}')


SVM Metrics:
Accuracy: 0.9404
Precision: 0.9399179178125057
Recall: 0.9394223313176161
F-Measure: 0.9395137440765534
Random Forest Metrics:
Accuracy: 0.9704
Precision: 0.9702675065275924
Recall: 0.970110018819363
F-Measure: 0.9701627566191542


In [18]:
print("SVM Confusion Matrix:")
print(confusion_matrix(y_test, svm_pred))

print("Random Forest Confusion Matrix:")
print(confusion_matrix(y_test, rf_pred))


SVM Confusion Matrix:
[[ 957    0    4    1    1    6    9    1    0    1]
 [   0 1122    3    2    0    1    2    1    4    0]
 [   8    6  967   11    3    3    7    8   17    2]
 [   4    3   16  947    1   16    0    9   12    2]
 [   1    1   10    1  942    2    4    2    3   16]
 [  10    4    3   36    6  803   13    1   14    2]
 [   9    2   13    1    5   16  910    1    1    0]
 [   1    8   21   10    8    1    0  957    3   19]
 [   8    4    6   25    7   26    6    7  877    8]
 [   7    7    2   11   33    4    0   18    5  922]]
Random Forest Confusion Matrix:
[[ 971    0    0    0    0    2    3    1    3    0]
 [   0 1127    2    2    0    1    2    0    1    0]
 [   6    0 1002    5    3    0    3    8    5    0]
 [   1    0    9  972    0    9    0    9    8    2]
 [   1    0    0    0  955    0    5    1    4   16]
 [   5    1    1    9    2  860    5    2    5    2]
 [   7    3    0    0    3    3  937    0    5    0]
 [   1    4   20    2    0    0    0  989   

In [19]:
# SVM ROC and AUC
fpr_svm, tpr_svm, _ = roc_curve(y_test, svm_model.decision_function(X_test), pos_label=1)
roc_auc_svm = auc(fpr_svm, tpr_svm)

# Random Forest ROC and AUC
fpr_rf, tpr_rf, _ = roc_curve(y_test, rf_model.predict_proba(X_test)[:, 1], pos_label=1)
roc_auc_rf = auc(fpr_rf, tpr_rf)

# Plot ROC curves
plt.figure(figsize=(8, 6))
plt.plot(fpr_svm, tpr_svm, color='blue', lw=2, label=f'SVM ROC curve (AUC = {roc_auc_svm:.2f})')
plt.plot(fpr_rf, tpr_rf, color='red', lw=2, label=f'Random Forest ROC curve (AUC = {roc_auc_rf:.2f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc='lower right')
plt.show()


ValueError: y should be a 1d array, got an array of shape (10000, 10) instead.

In [20]:
# If y_test is one-hot encoded, convert it to a 1D array
if len(y_test.shape) > 1 and y_test.shape[1] > 1:
    y_test = np.argmax(y_test, axis=1)

# SVM ROC and AUC
fpr_svm, tpr_svm, _ = roc_curve(y_test, svm_model.decision_function(X_test), pos_label=1)
roc_auc_svm = auc(fpr_svm, tpr_svm)

# Random Forest ROC and AUC
fpr_rf, tpr_rf, _ = roc_curve(y_test, rf_model.predict_proba(X_test)[:, 1], pos_label=1)
roc_auc_rf = auc(fpr_rf, tpr_rf)

# Plot ROC curves
plt.figure(figsize=(8, 6))
plt.plot(fpr_svm, tpr_svm, color='blue', lw=2, label=f'SVM ROC curve (AUC = {roc_auc_svm:.2f})')
plt.plot(fpr_rf, tpr_rf, color='red', lw=2, label=f'Random Forest ROC curve (AUC = {roc_auc_rf:.2f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc='lower right')
plt.show()


ValueError: y should be a 1d array, got an array of shape (10000, 10) instead.

In [22]:
y_proba_rf = rf_model.predict_proba(X_test)
roc_auc = roc_auc_score(y_test, y_proba_rf, multi_class="ovr")
print(f"ROC AUC for Random Forest: {roc_auc:.2f}")

fpr, tpr, _ = roc_curve(y_val, y_proba_rf[:, 0], pos_label=0)
plt.figure()
plt.plot(fpr, tpr, label="Random Forest (AUC = %.2f)" % roc_auc)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

     

NameError: name 'roc_auc_score' is not defined