In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist, cifar10
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
from sklearn.model_selection import train_test_split
import tensorflow as tf


In [3]:

def compress_image(image_path, output_path_jpeg, output_path_png, quality=30):
    # Read the image
    img = cv2.imread(content/img.jpg)

    # Convert to RGB (OpenCV loads images in BGR format)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Compress as JPEG (Lossy Compression)
    cv2.imwrite(output_path_jpeg, img, [int(cv2.IMWRITE_JPEG_QUALITY), quality])

    # Compress as PNG (Lossless Compression)
    cv2.imwrite(output_path_png, img, [int(cv2.IMWRITE_PNG_COMPRESSION), 9])

    print(f"Compressed images saved as {output_path_jpeg} and {output_path_png}")

In [4]:

# Task 2: CNN on MNIST Dataset

def build_mnist_cnn():
    model = keras.Sequential([
        layers.Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Conv2D(64, kernel_size=(3, 3), activation='relu'),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Flatten(),
        layers.Dense(128, activation='relu'),
        layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model


In [5]:

# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [6]:
# Normalize and reshape data
x_train = x_train.reshape(-1, 28, 28, 1) / 255.0
x_val = x_val.reshape(-1, 28, 28, 1) / 255.0
x_test = x_test.reshape(-1, 28, 28, 1) / 255.0


In [7]:
# Train CNN on MNIST
epochs = 10
mnist_model = build_mnist_cnn()
history = mnist_model.fit(x_train, y_train, epochs=epochs, validation_data=(x_val, y_val))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 50s 32ms/step - accuracy: 0.9010 - loss: 0.3208 - val_accuracy: 0.9820 - val_loss: 0.0555
Epoch 2/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 82s 32ms/step - accuracy: 0.9843 - loss: 0.0499 - val_accuracy: 0.9861 - val_loss: 0.0465
Epoch 3/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 48s 32ms/step - accuracy: 0.9899 - loss: 0.0307 - val_accuracy: 0.9895 - val_loss: 0.0346
Epoch 4/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 86s 35ms/step - accuracy: 0.9932 - loss: 0.0208 - val_accuracy: 0.9889 - val_loss: 0.0376
Epoch 5/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 50s 33ms/step - accuracy: 0.9953 - loss: 0.0150 - val_accuracy: 0.9911 - val_loss: 0.0346
Epoch 6/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 81s 32ms/step - accuracy: 0.9964 - loss: 0.0118 - val_accuracy: 0.9882 - val_loss: 0.0428
Epoch 7/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 82s 32ms/step - accuracy: 0.9965 - loss: 0.0097 - val_accuracy: 0.9910 - val_loss: 0.0383
Epoch 8/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 81s 32ms/step - accuracy: 0.9972 -

In [8]:
mnist_predictions = mnist_model.predict(x_test).argmax(axis=1)
print(classification_report(y_test, mnist_predictions))
print("Confusion Matrix:")
print(confusion_matrix(y_test, mnist_predictions))


313/313 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       980
           1       0.99      1.00      0.99      1135
           2       0.99      0.99      0.99      1032
           3       0.99      0.99      0.99      1010
           4       1.00      0.99      0.99       982
           5       0.98      0.99      0.99       892
           6       0.99      0.99      0.99       958
           7       0.99      0.98      0.99      1028
           8       0.99      0.99      0.99       974
           9       0.99      0.98      0.99      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

Confusion Matrix:
[[ 977    0    0    0    0    0    1    1    1    0]
 [   0 1135    0    0    0    0    0    0    0    0]
 [   2    1 1018    5    0    0    0    5    1    0]
 [   0    1    0 1004 

In [9]:
def build_cifar10_cnn():
    model = keras.Sequential([
        layers.Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(32, 32, 3)),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Conv2D(64, kernel_size=(3, 3), activation='relu'),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Flatten(),
        layers.Dense(128, activation='relu'),
        layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

In [10]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)


170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 12s 0us/step


In [11]:
x_train = x_train / 255.0
x_val = x_val / 255.0
x_test = x_test / 255.0

In [12]:
cifar_model = build_cifar10_cnn()
history = cifar_model.fit(x_train, y_train, epochs=epochs, validation_data=(x_val, y_val))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 57s 45ms/step - accuracy: 0.3916 - loss: 1.6792 - val_accuracy: 0.5530 - val_loss: 1.2695
Epoch 2/10
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 55s 44ms/step - accuracy: 0.6004 - loss: 1.1487 - val_accuracy: 0.6157 - val_loss: 1.0877
Epoch 3/10
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 83s 45ms/step - accuracy: 0.6564 - loss: 0.9839 - val_accuracy: 0.6571 - val_loss: 0.9857
Epoch 4/10
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 81s 44ms/step - accuracy: 0.6960 - loss: 0.8734 - val_accuracy: 0.6546 - val_loss: 0.9923
Epoch 5/10
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 84s 45ms/step - accuracy: 0.7289 - loss: 0.7766 - val_accuracy: 0.6741 - val_loss: 0.9472
Epoch 6/10
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 81s 45ms/step - accuracy: 0.7500 - loss: 0.7150 - val_accuracy: 0.6645 - val_loss: 0.9953
Epoch 7/10
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 81s 44ms/step - accuracy: 0.7777 - loss: 0.6433 - val_accuracy: 0.6844 - val_loss: 0.9507
Epoch 8/10
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 84s 46ms/step - accuracy: 0.7986 -

In [13]:
cifar_predictions = cifar_model.predict(x_test).argmax(axis=1)
print(classification_report(y_test, cifar_predictions))
print("Confusion Matrix:")
print(confusion_matrix(y_test, cifar_predictions))

313/313 ━━━━━━━━━━━━━━━━━━━━ 7s 23ms/step
              precision    recall  f1-score   support

           0       0.77      0.71      0.74      1000
           1       0.80      0.80      0.80      1000
           2       0.53      0.67      0.59      1000
           3       0.52      0.46      0.49      1000
           4       0.56      0.69      0.62      1000
           5       0.61      0.55      0.58      1000
           6       0.77      0.75      0.76      1000
           7       0.80      0.70      0.75      1000
           8       0.79      0.81      0.80      1000
           9       0.79      0.75      0.77      1000

    accuracy                           0.69     10000
   macro avg       0.69      0.69      0.69     10000
weighted avg       0.69      0.69      0.69     10000

Confusion Matrix:
[[713  30  74  17  45   4   9  10  73  25]
 [ 17 798  18  15  11   7  16   5  29  84]
 [ 46   3 666  52 101  43  41  20  15  13]
 [ 19   6 111 459 117 165  60  28  20  15]
 [ 14   3